platform_dbt:
  outputs:
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'xxx') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'xxx') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'xxx') }}"
      role: "ACCOUNTADMIN"
      warehouse: "PLATFORM_WH"
      database: "PLATFORM_DB"
      schema: SILVER
      threads: 2
  target: dev
