platform_dbt:
  outputs:
    dev:
      dbname: warehouse
      host: postgres
      pass: "{{ env_var('POSTGRES_PASSWORD', 'svc_dwh') }}"
      port: 5432
      schema: dbt
      threads: 2
      type: postgres
      user: "{{ env_var('POSTGRES_USER', 'svc_dwh') }}"
  target: dev
